version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ADMIN  # define in execution time
      POSTGRES_DB: sensors_logs_db
    volumes:
      - ../src/db/scripts:/docker-entrypoint-initdb.d
      - ../data:/data  # mount local folder with json
    ports:
      - "5432:5432"