-- poblar tabla event_types con los tipos de eventos únicos
INSERT INTO event_types (event_name)
SELECT DISTINCT raw_payload->>'event_type'
FROM landing_logs;

-- poblar tabla sensors con los sensores únicos
INSERT INTO sensors (sensor_name, description)
SELECT DISTINCT raw_payload->>'sensor_id', 'Autogenerated from landing logs'
FROM landing_logs;

-- poblar tabla sensor_events con los datos transformados
INSERT INTO sensor_events (sensor_id, event_type_id, timestamp, duration_seconds)
SELECT 
    s.sensor_id,
    et.event_type_id,
    (l.raw_payload->>'timestamp')::timestamp,
    (l.raw_payload->>'duration_seconds')::int
FROM landing_logs l
JOIN sensors s ON s.sensor_name = l.raw_payload->>'sensor_id'
JOIN event_types et ON et.event_name = l.raw_payload->>'event_type';
