FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY data/ ./data/
COPY src/ ./src/
COPY main.py .

ENV RUNENV=gcp
ENV PORT=80

EXPOSE 80

CMD ["python", "main.py"]